name: Wi-Fi Speed Monitor

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  speed-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decrypt environment file
        run: |
          echo "${{ secrets.CONFIG_PASSWORD }}" | python encrypt_decrypt_config.py d
        env:
          CONFIG_PASSWORD: ${{ secrets.CONFIG_PASSWORD }}

      - name: Run speed test script
        run: python speedtest_check.py
